# Generated by Django 4.0 on 2026-09-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipo', '0002_perfil_alcance_territorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SipoFichaIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social_id', models.CharField(blank=True, max_length=50, null=True)),
                ('razon_social_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('obra', models.CharField(blank=True, max_length=255, null=True)),
                ('centro_costo_id', models.CharField(blank=True, max_length=100, null=True)),
                ('centro_costo_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('correo_jefe_directo', models.EmailField(blank=True, max_length=254, null=True)),
                ('correo_admin_obra', models.EmailField(blank=True, max_length=254, null=True)),
                ('nombres', models.CharField(blank=True, max_length=150, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('rut', models.CharField(blank=True, max_length=20, null=True)),
                ('afp', models.CharField(blank=True, max_length=100, null=True)),
                ('isapre_fonasa', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=50, null=True)),
                ('edad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('comuna', models.CharField(blank=True, max_length=100, null=True)),
                ('email_personal', models.EmailField(blank=True, max_length=254, null=True)),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_cuenta', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_cuenta', models.CharField(blank=True, max_length=50, null=True)),
                ('sueldo_liquido', models.PositiveIntegerField(blank=True, null=True)),
                ('dias_contrato', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo_jornada', models.CharField(blank=True, max_length=30, null=True)),
                ('horario', models.CharField(blank=True, max_length=120, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('doc_titulo', models.FileField(blank=True, null=True, upload_to='fichas_ingreso/adjuntos/%Y/%m/')),
                ('doc_afp', models.FileField(blank=True, null=True, upload_to='fichas_ingreso/adjuntos/%Y/%m/')),
                ('doc_salud', models.FileField(blank=True, null=True, upload_to='fichas_ingreso/adjuntos/%Y/%m/')),
                ('doc_cedula', models.FileField(blank=True, null=True, upload_to='fichas_ingreso/adjuntos/%Y/%m/')),
                ('creado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('creado_por_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sipo_ficha_ingreso',
                'ordering': ['-id'],
            },
        ),
    ]
