# Generated by Django 4.0 on 2026-09-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipo', '0003_ficha_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='sipofichaingreso',
            name='aprobado_admin_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sipofichaingreso',
            name='aprobado_admin_por',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sipofichaingreso',
            name='aprobado_jefe_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sipofichaingreso',
            name='aprobado_jefe_por',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sipofichaingreso',
            name='aprobado_rrhh_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sipofichaingreso',
            name='aprobado_rrhh_por',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sipofichaingreso',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_JEFE', 'Pendiente aprobación Jefe directo'), ('PENDIENTE_ADMIN', 'Pendiente aprobación Administrador de obra'), ('PENDIENTE_RRHH', 'Pendiente aprobación RRHH'), ('APROBADA', 'Aprobada')], db_index=True, default='PENDIENTE_JEFE', max_length=30),
        ),
    ]
