CREATE_FIELDS = (
    'cf_rrhh_sip_obra_candidato_tratamiento',
    'cf_rrhh_sip_obra_candidato_rut',
    'cf_rrhh_sip_obra_candidato_nombre',
    'cf_rrhh_sip_obra_candidato_segundo_nombre',
    'cf_rrhh_sip_obra_candidato_ap',
    'cf_rrhh_sip_obra_candidato_am',
    'cf_rrhh_sip_obra_candidato_genero',
    'cf_rrhh_sip_obra_candidato_fecha_nacimiento',
    'cf_rrhh_sip_obra_candidato_pais_nacimiento',
    'cf_rrhh_sip_obra_candidato_region_nacimiento',
    'cf_rrhh_sip_obra_candidato_nacionalidad',
    'cf_rrhh_sip_obra_candidato_nacionalidad_ext',
    'cf_rrhh_sip_obra_candidato_region',
    'cf_rrhh_sip_obra_candidato_ciudad',
    'cf_rrhh_sip_obra_candidato_comuna',
    'cf_rrhh_sip_obra_candidato_villa',
    'cf_rrhh_sip_obra_candidato_direccion',
    'cf_rrhh_sip_obra_candidato_numero_dire',
    'cf_rrhh_sip_obra_candidato_num_depto',
    'cf_rrhh_sip_obra_candidato_estado_civil',
    'cf_rrhh_sip_obra_candidato_telefono',
    'cf_rrhh_sip_obra_candidato_correo',
    'cf_rrhh_sip_obra_candidato_metodo_pago',
    'cf_rrhh_sip_obra_candidato_banco',
    'cf_rrhh_sip_obra_candidato_numcta',
    'cf_rrhh_sip_obra_candidato_anticipo',
    'cf_rrhh_sip_obra_candidato_nomcar',
    'cf_rrhh_sip_obra_candidato_jefe_user_id',
    'cf_rrhh_sip_obra_candidato_jefe_nombre',
    'cf_rrhh_sip_obra_candidato_jefe_correo',
    'cf_rrhh_sip_obra_candidato_horario_trabajo',
    'cf_rrhh_sip_obra_candidato_sueldo',
    'cf_rrhh_sip_obra_candidato_cuenta_gasto',
    'cf_rrhh_sip_obra_candidato_tipo_contrato',
    'cf_rrhh_sip_obra_candidato_fecha_ingreso',
    'cf_rrhh_sip_obra_candidato_termino_contrato',
    'cf_rrhh_sip_obra_candidato_fecha_termino_ito',
    'cf_rrhh_sip_obra_candidato_jubilado',
    'cf_rrhh_sip_obra_candidato_nom_afp',
    'cf_rrhh_sip_obra_candidato_nom_salud',
    'cf_rrhh_sip_obra_candidato_valor_plan',
    'cf_rrhh_sip_obra_candidato_valor_uf',
    'cf_rrhh_sip_obra_candidato_seguro_covid',
    'cf_rrhh_sip_obra_candidato_ci',
    'cf_rrhh_sip_obra_candidato_afp',
    'cf_rrhh_sip_obra_candidato_salud',
    'cf_rrhh_sip_obra_candidato_domi',
    'cf_rrhh_sip_obra_candidato_doc_jubi',
    'cf_rrhh_sip_obra_candidato_jubi',
    'cf_rrhh_sip_obra_candidato_visa',
    'cf_rrhh_sip_obra_candidato_permiso_trabajo',
    'cf_rrhh_sip_obra_candidato_copia_seguro_covid',
)

UPPER_FIELDS = (
    'cf_rrhh_sip_obra_candidato_nombre',
    'cf_rrhh_sip_obra_candidato_segundo_nombre',
    'cf_rrhh_sip_obra_candidato_ap',
    'cf_rrhh_sip_obra_candidato_am',
    'cf_rrhh_sip_obra_candidato_nomcar',
    'cf_rrhh_sip_obra_candidato_direccion',
    'cf_rrhh_sip_obra_candidato_villa',
)

REQUIRED_FIELDS = (
    'cf_rrhh_sip_obra_candidato_tratamiento',
    'cf_rrhh_sip_obra_candidato_rut',
    'cf_rrhh_sip_obra_candidato_nombre',
    'cf_rrhh_sip_obra_candidato_ap',
    'cf_rrhh_sip_obra_candidato_am',
    'cf_rrhh_sip_obra_candidato_genero',
    'cf_rrhh_sip_obra_candidato_fecha_nacimiento',
    'cf_rrhh_sip_obra_candidato_estado_civil',
    'cf_rrhh_sip_obra_candidato_telefono',
    'cf_rrhh_sip_obra_candidato_correo',
    'cf_rrhh_sip_obra_candidato_pais_nacimiento',
    'cf_rrhh_sip_obra_candidato_region_nacimiento',
    'cf_rrhh_sip_obra_candidato_nacionalidad',
    'cf_rrhh_sip_obra_candidato_region',
    'cf_rrhh_sip_obra_candidato_ciudad',
    'cf_rrhh_sip_obra_candidato_comuna',
    'cf_rrhh_sip_obra_candidato_direccion',
    'cf_rrhh_sip_obra_candidato_numero_dire',
    'cf_rrhh_sip_obra_candidato_metodo_pago',
    'cf_rrhh_sip_obra_candidato_banco',
    'cf_rrhh_sip_obra_candidato_numcta',
    'cf_rrhh_sip_obra_candidato_nom_afp',
    'cf_rrhh_sip_obra_candidato_nom_salud',
    'cf_rrhh_sip_obra_candidato_jubilado',
    'cf_rrhh_sip_obra_candidato_nomcar',
    'cf_rrhh_sip_obra_candidato_jefe_user_id',
    'cf_rrhh_sip_obra_candidato_jefe_nombre',
    'cf_rrhh_sip_obra_candidato_horario_trabajo',
    'cf_rrhh_sip_obra_candidato_sueldo',
    'cf_rrhh_sip_obra_candidato_cuenta_gasto',
    'cf_rrhh_sip_obra_candidato_tipo_contrato',
    'cf_rrhh_sip_obra_candidato_fecha_ingreso',
)


def is_blank_value(value) -> bool:
    if value is None:
        return True
    if isinstance(value, str) and value.strip() == '':
        return True
    return False
